### PR TITLE
feat: switch to sqlite

### LINKED ISSUE #60: Change database layer to use sqlite
Right now we are using a sled db which is hard to migrate and almost impossible to read from from outside of the application. Hence I propose migrating to sqlite

### PR DESCRIPTION
**Pull request by Restioson**
Fixes #60 

I did make one query now be fallible - it will now return an error if there is an invalid zap in the DB.

Unfortunately I'm not sure how to test this end-to-end :sweat_smile:

### CODE REVIEW

**Comment by Restioson** [comment]
Looks like I left the `dbg` in as well. I'll take a look at this on Wednesday; it was working for me at some point, so maybe I undid the thing that made it work

**Review by bonomat — APPROVED** [review]
Nice. Thank you. I'll give it a try locally

**Comment by bonomat** [comment]
I get the same error as @luckysori 

```
docker logs -f nostrdice
2024-08-21 07:54:48  INFO nostr_dice::logger: Initialized logger
2024-08-21 07:54:48 DEBUG hyper::client::connect::dns: resolving host="bob"
2024-08-21 07:54:48 DEBUG hyper::client::connect::http: connecting to 172.18.0.4:10009
2024-08-21 07:54:48 DEBUG hyper::client::connect::http: connected to 172.18.0.4:10009
2024-08-21 07:54:48 DEBUG hyper::client::pool: pooling idle connection for ("https", bob:10009)
2024-08-21 07:54:48  INFO nostr_dice: Connected to LND: 03eb56540e181b297224c8a4820db70e8818b6925dd52e77a2a7f593f6f503bf53
Error: Failed to open database file

Caused by:
    0: error returned from database: (code: 14) unable to open database file
    1: (code: 14) unable to open database file

```

**Comment by Restioson** [comment]
How are you running this (compose or just the container)? Also, did you get any other errors (e.g. during container build)? I'm not sure how this is possible given that the settings dictate that it should create the database file if it's missing. Perhaps the data folder itself is missing?

**Comment by Restioson** [comment]
For me, `just all` works:
```
docker logs -f nostrdice
2024-08-22 13:55:47  INFO nostr_dice::logger: Initialized logger
2024-08-22 13:55:47 DEBUG hyper::client::connect::dns: resolving host="bob"
2024-08-22 13:55:47 DEBUG hyper::client::connect::http: connecting to 172.26.0.3:10009
2024-08-22 13:55:47 DEBUG hyper::client::connect::http: connected to 172.26.0.3:10009
2024-08-22 13:55:47 DEBUG hyper::client::pool: pooling idle connection for ("https", bob:10009)
2024-08-22 13:55:47  INFO nostr_dice: Connected to LND: 0226e59f462f11c864a466f7451493d2ab2f85e16990279e7b705f93b74a633e27
2024-08-22 13:55:47  INFO nostr_dice: Webserver running on http://0.0.0.0:1993
2024-08-22 13:55:47  INFO nostr_dice::subscriber: Starting invoice subscription
2024-08-22 13:55:47 DEBUG hyper::client::pool: reuse idle connection for ("https", bob:10009)
2024-08-22 13:55:47 DEBUG tungstenite::handshake::client: Client handshake done.
2024-08-22 13:55:47 DEBUG nostr_dice::social_updates: No winners in this round, not posting anything
2024-08-22 13:55:47 DEBUG reqwest::connect: starting new connection: http://nostr-rs-relay:8080/
2024-08-22 13:55:47 DEBUG nostr_dice::nonce: New active nonce commitment=0751573ddcaa823a9bf3102217354bf758af38f70825c6e9e01c1a38a3af1d73 commitment_event_id=fa918f889b92c154711cd49fc52af07375bf26237d1de09798c72dc43654b26f
2024-08-22 13:56:17 DEBUG nostr_dice::nonce: Nonce has expired commitment=0751573ddcaa823a9bf3102217354bf758af38f70825c6e9e01c1a38a3af1d73
2024-08-22 13:56:17 DEBUG nostr_dice::nonce: Waiting to reveal expired nonce commitment=0751573ddcaa823a9bf3102217354bf758af38f70825c6e9e01c1a38a3af1d73
2024-08-22 13:56:17 DEBUG nostr_dice::nonce: New active nonce commitment=e9f63aa0dbd6e940f8fdabe5dd93b4d6751fc3fe503b8eb09fa0f41ed43a69f3 commitment_event_id=86ca8bb8e80649cb8bcea4b3d44e71bc19be44ff5c13c6b0304b46f47ca0ada7
```

**Comment by bonomat** [comment]
My mistake 🙈 the issue was that `data/zaps.db` was still there from sled-db times and it was a directory. `just wipe` didn't work because it only deletes files not directories, hence, the file was still there and `nostrdice` couldn't create a new file. 

Thank @Restioson and sorry for the confusion.

**Comment by bonomat** [comment]
Tested it locally successfully including running `just test`.

**Pull request merged**
